spring.application.name=full-stack-backend
spring.datasource.url=jdbc:mysql://localhost:3306/fullstack_db
spring.datasource.username=root
spring.datasource.password=munna@2858

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080

jwt.secret=Y29tcGxldGVseS1yYW5kb20tc2VjcmV0LW1lbnQtZm9yLWp3dC1zaWduYXR1cmU=
jwt.expiration-ms=86400000
